# Cut a release whenever a new tag is pushed to the repo.
# You should use an annotated tag, like `git tag -a v1.2.3`
# and put the release notes into the commit message for the tag.
name: Release

on:
  # Can be triggered from the tag.yaml workflow
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
  # Or, developers can manually push a tag from their clone
  # push:
  #   tags:
  #     - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@v6
    with:
      # If called from tag.yaml, the new tag isn't the triggering event
      tag_name: ${{ inputs.tag_name || github.ref }}
      release_files: rules_mylang-*.tar.gz
