# Cut a release whenever a new tag is pushed to the repo.
# You should use an annotated tag, like `git tag -a v1.2.3`
# and put the release notes into the commit message for the tag.
name: Release

on:
  # Can be triggered from the tag.yaml workflow
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
  # Or, developers can manually push a tag from their clone
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@b3e3065d43517a52c05015ad16587bd2d903cfdb # https://github.com/bazel-contrib/.github/pull/20
    with:
      tag_name: ${{ inputs.tag_name }}
      prerelease: false
      release_files: rules_mylang-*.tar.gz
