# Tag a new release
# This is easier than having to run manual `git` operations on a local clone.
# It also runs on a schedule so we don't leave commits unreleased indefinitely
# (avoiding users having to ping "hey could someone cut a release").

name: Tag a Release
on:
  # Allow devs to tag manually through the GitHub UI.
  # For example after landing a fix that customers are waiting for.
  workflow_dispatch:

  # Run every Monday at 3PM UTC (8AM PST)
  # NB: would prefer to trigger less frequently, perhaps bi-weekly, see
  # https://medium.com/@VeselyCodes/bi-weekly-github-actions-7bea6be7bd96
  schedule:
    - cron: "0 15 * * 1"

jobs:
  tag:
    permissions:
      # create tag
      contents: write
    runs-on: ubuntu-latest
    outputs:
      new-tag: ${{ steps.ccv.outputs.new-tag }}
      new-tag-version: ${{steps.ccv.outputs.new-tag-version}}
    steps:
      - uses: actions/checkout@v4
        with:
          # Need enough history to find the prior release tag
          fetch-depth: 0
      - name: Bump tag if necessary
        id: ccv
        uses: smlx/ccv@7318e2f25a52dcd550e75384b84983973251a1f8 # 4 Dec 2024
  release:
    needs: tag
    uses: ./.github/workflows/release.yml
    with:
      tag_name: ${{ needs.tag.outputs.new-tag-version }}
    if: needs.tag.outputs.new-tag == 'true'
    permissions:
      # create release
      contents: write